// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

// "use client";

// import { AppBar, Toolbar, Typography, Button, Container, Box } from "@mui/material";
// import Link from "next/link";
// import "./globals.css";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body style={{ margin: 0, fontFamily: "Roboto, sans-serif" }}>
//         {/* Header */}
//         <AppBar position="static" sx={{ backgroundColor: "#1976d2" }}>
//           <Toolbar>
//             <Typography variant="h6" sx={{ flexGrow: 1 }}>
//               My Next.js App
//             </Typography>

//             <Button color="inherit" component={Link} href="/">
//               Home
//             </Button>
//             <Button color="inherit" component={Link} href="/todo">
//               To-Do
//             </Button>
//             <Button color="inherit" component={Link} href="/slideshow">
//               Slideshow
//             </Button>
//           </Toolbar>
//         </AppBar>

//         {/* Main Page Content */}
//         <Container maxWidth="md" sx={{ minHeight: "80vh", py: 4 }}>
//           {children}
//         </Container>

//         {/* Footer */}
//         <Box
//           component="footer"
//           sx={{
//             py: 2,
//             textAlign: "center",
//             backgroundColor: "#f1f1f1",
//             borderTop: "1px solid #ddd",
//           }}
//         >
//           {/* <Typography variant="body2" color="text.secondary">
//             © {new Date().getFullYear()} My Next.js App. All rights reserved.
//           </Typography> */}
//         </Box>
//       </body>
//     </html>
//   );
// }


"use client";
import { CssBaseline, Container } from "@mui/material";
import { createTheme, ThemeProvider } from "@mui/material/styles";

const theme = createTheme({
  palette: {
    mode: "light",
    primary: { main: "#1976d2" },
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Container maxWidth="md" sx={{ mt: 4 }}>
            {children}
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
